### ISSUE TITLE
Angular 7 Intergartion

### ISSUE THREAD

**Issue by tusharmestri** [dmytroyarmak/angular-flip-clock#4]
It is not issued just I wanted to know how to integrate angular-flip-clock with Angular 7. Any ref for that

**Comment by dmytroyarmak** [comment]
@tusharmestri This library was created for AngularJS 1.x and I don't know if there is Angular 7 version of http://flipclockjs.com/.

The code is pretty simple, so you can even try to write your own version ;)

**Comment by dmytroyarmak** [comment]
Also, after v1 of FlipClock.js is released (that doesn't have jQuery as dependency) it will be easier to integrate it with Angular 7: https://github.com/objectivehtml/FlipClock/issues/312

**Comment by almgwary** [comment]
please close the issue
